version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Strong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: ./backend
    container_name: fast_api_backend
    volumes:
      - ./backend:/app
    environment:
      - MASTER_DB=mssql+aioodbc://sa:Strong!Passw0rd@db:1433/master?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes
      - ASYNC_DATABASE_URL=mssql+aioodbc://sa:Strong!Passw0rd@db:1433/insurance_db?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: nuxt_frontend
    environment:
      - NUXT_PUBLIC_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mssql_data:
